"use client"

import React, { createContext, useContext, useState, useEffect } from "react"

type Language = "en" | "zh-CN" | "zh-TW" | "ja" | "ru"

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export const translations: Record<Language, Record<string, string>> = {
  en: {
    // Header
    community: "Community",
    developers: "Developers",
    docs: "Docs",
    launchApp: "Launch App",
    tradePerps: "Trade Perps",
    memePerps: "Trade Meme Perps",

    // Hero
    heroTitle: "Meme Perpetuals on Solana",
    heroSubtitle: "100x leverage on every meme. Long the pump, short the dump.",
    volume24h: "24H Volume",
    cumulativeVolume: "Cumulative Volume",
    addresses: "Active Traders",
    
    // DEX Section
    dexTitle: "Advanced order controls for professional traders",
    startTrading: "Launch App",
    lowFees: "Advanced Orders",
    minimalSlippage: "Real-time Metrics",
    selfCustody: "Portfolio View",
    lightningFast: "Low-latency UI",
    
    // Trade Section
    tradeTitle: "Trade Anytime, Anywhere",
    tradeDescription: "Access Perpolis from any device. Fast, reliable, and built for professional traders.",
    
    // Features
    featuresTitle: "Built for Professional Traders",
    featuresSubtitle: "Fast execution, transparent funding, and advanced risk controls",
    ultraDeepLiquidity: "Session Protection",
    ultraDeepDesc: "Your sessions are isolated and fully protected. Trade with confidence in a secure environment.",
    highPerformance: "Risk Controls",
    highPerformanceDesc: "Set stop losses, take profits, and manage your positions with precision.",
    provenSecurity: "Transparent Funding",
    provenSecurityDesc: "Real-time funding rates. No hidden fees or surprises.",
    oneAppUnlimited: "Advanced Charting",
    oneAppDesc: "Professional-grade charts with technical indicators and drawing tools.",
    
    // Roadmap
    roadmapTitle: "Roadmap",
    roadmapSubtitle: "Building the future of perpetuals trading",
    q1: "Q1 2026",
    q1Title: "Perpolis V1 Launch",
    q1Desc: "Web and mobile trading terminal with advanced order types",
    q2: "Q2 2026",
    q2Title: "Advanced Analytics",
    q2Desc: "Real-time portfolio analytics and performance tracking",
    q3: "Q3 2026",
    q3Title: "Social Trading",
    q3Desc: "Copy successful traders and share strategies",
    q4: "Q4 2026",
    q4Title: "Mobile App",
    q4Desc: "Native iOS and Android applications for on-the-go trading",
    
    // Team
    teamTitle: "Our Team Comes From",
    
    // Footer
    footerTagline: "Fast execution, clear risk controls, and a clean trading terminal",
    products: "Products",
    spotTrading: "Perpetuals",
    futuresTrading: "Futures",
    eStrategy: "Markets",
    earn: "Fees",
    resources: "Resources",
    documentation: "Docs",
    api: "API",
    github: "GitHub",
    blog: "Status",
    legal: "Legal",
    termsOfService: "Terms of Service",
    privacyPolicy: "Privacy Policy",
    cookiePolicy: "Cookie Policy",
    copyright: "© 2026 Perpolis. All rights reserved.",
    builtForTraders: "Built for traders, by traders.",
    
    // Terms of Service
    termsTitle: "Terms of Service",
    termsAcceptance: "1. Acceptance of Terms",
    termsAcceptanceText: "By accessing and using Perpolis, you accept and agree to be bound by the terms and provision of this agreement. If you do not agree to abide by the above, please do not use this service.",
    termsLicense: "2. Use License",
    termsLicenseText: "Permission is granted to temporarily access the materials (information or software) on Perpolis for personal, non-commercial transitory viewing only. This is the grant of a license, not a transfer of title.",
    termsLicenseRestrictions: "Under this license you may not:",
    termsLicenseList1: "Modify or copy the materials",
    termsLicenseList2: "Use the materials for any commercial purpose or for any public display",
    termsLicenseList3: "Attempt to reverse engineer any software contained on Perpolis",
    termsLicenseList4: "Remove any copyright or other proprietary notations from the materials",
    termsRisks: "3. Trading Risks",
    termsRisksText1: "Trading cryptocurrencies and derivatives carries a high level of risk and may not be suitable for all investors. Before deciding to trade, you should carefully consider your investment objectives, level of experience, and risk appetite.",
    termsRisksText2: "The possibility exists that you could sustain a loss of some or all of your initial investment and therefore you should not invest money that you cannot afford to lose.",
    termsAccounts: "4. User Accounts",
    termsAccountsText1: "When you create an account with us, you must provide information that is accurate, complete, and current at all times. Failure to do so constitutes a breach of the Terms, which may result in immediate termination of your account.",
    termsAccountsText2: "You are responsible for safeguarding the password that you use to access the Service and for any activities or actions under your password.",
    termsProhibited: "5. Prohibited Activities",
    termsProhibitedText: "You may not access or use the platform for any purpose other than that for which we make the platform available. Prohibited activities include but are not limited to:",
    termsProhibitedList1: "Market manipulation or fraudulent trading activities",
    termsProhibitedList2: "Automated trading without explicit authorization",
    termsProhibitedList3: "Attempting to interfere with the proper working of the platform",
    termsProhibitedList4: "Circumventing any security features",
    termsProhibitedList5: "Engaging in money laundering or terrorist financing",
    termsLiability: "6. Limitation of Liability",
    termsLiabilityText: "In no event shall Perpolis or its suppliers be liable for any damages (including, without limitation, damages for loss of data or profit, or due to business interruption) arising out of the use or inability to use the materials on Perpolis, even if Perpolis or an authorized representative has been notified orally or in writing of the possibility of such damage.",
    termsModifications: "7. Modifications",
    termsModificationsText: "Perpolis may revise these terms of service at any time without notice. By using this platform you are agreeing to be bound by the then current version of these terms of service.",
    termsContact: "8. Contact Information",
    termsContactText: "If you have any questions about these Terms, please contact us through our official communication channels.",
    lastUpdated: "Last updated: April 2026",
    
    // Privacy Policy
    privacyTitle: "Privacy Policy",
    privacyCollection: "1. Information We Collect",
    privacyCollectionText: "We collect several different types of information for various purposes to provide and improve our service to you.",
    privacyPersonalData: "Personal Data",
    privacyPersonalDataText: "While using our platform, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you. This may include:",
    privacyDataList1: "Email address",
    privacyDataList2: "Wallet addresses",
    privacyDataList3: "Trading history and transaction data",
    privacyDataList4: "Device and browser information",
    privacyDataList5: "IP address and location data",
    privacyUsage: "2. How We Use Your Information",
    privacyUsageText: "Perpolis uses the collected data for various purposes:",
    privacyUsageList1: "To provide and maintain our trading platform",
    privacyUsageList2: "To notify you about changes to our service",
    privacyUsageList3: "To provide customer support",
    privacyUsageList4: "To detect, prevent and address technical issues and fraudulent activities",
    privacyUsageList5: "To comply with legal obligations and regulatory requirements",
    privacyUsageList6: "To provide analysis or valuable information to improve the service",
    privacySecurity: "3. Data Security",
    privacySecurityText1: "The security of your data is important to us. We implement industry-standard security measures to protect your personal information. However, remember that no method of transmission over the Internet or method of electronic storage is 100% secure.",
    privacySecurityText2: "Security measures we employ include:",
    privacySecurityList1: "Encryption of sensitive data in transit and at rest",
    privacySecurityList2: "Regular security audits and penetration testing",
    privacySecurityList3: "Multi-factor authentication options",
    privacySecurityList4: "Secure wallet infrastructure with cold storage solutions",
    privacySecurityList5: "Employee security training and access controls",
    privacyCookies: "4. Cookies and Tracking",
    privacyCookiesText1: "We use cookies and similar tracking technologies to track activity on our platform and hold certain information. Cookies are files with small amounts of data which may include an anonymous unique identifier.",
    privacyCookiesText2: "You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, you may not be able to use some portions of our platform.",
    privacyThirdParty: "5. Third-Party Services",
    privacyThirdPartyText1: "We may employ third-party companies and individuals to facilitate our service, provide the service on our behalf, perform service-related services, or assist us in analyzing how our service is used.",
    privacyThirdPartyText2: "These third parties have access to your personal data only to perform these tasks on our behalf and are obligated not to disclose or use it for any other purpose.",
    privacyRetention: "6. Data Retention",
    privacyRetentionText: "We will retain your personal data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use your data to the extent necessary to comply with our legal obligations, resolve disputes, and enforce our legal agreements and policies.",
    privacyRights: "7. Your Data Protection Rights",
    privacyRightsText: "Depending on your location, you may have the following data protection rights:",
    privacyRightsList1: "The right to access, update or delete your personal information",
    privacyRightsList2: "The right to rectification of inaccurate data",
    privacyRightsList3: "The right to object to processing of your data",
    privacyRightsList4: "The right to request restriction of processing",
    privacyRightsList5: "The right to data portability",
    privacyRightsList6: "The right to withdraw consent",
    privacyTransfers: "8. International Data Transfers",
    privacyTransfersText: "Your information, including personal data, may be transferred to and maintained on computers located outside of your state, province, country or other governmental jurisdiction where the data protection laws may differ from those of your jurisdiction.",
    privacyChildren: "9. Children's Privacy",
    privacyChildrenText: "Our service is not directed to anyone under the age of 18. We do not knowingly collect personally identifiable information from anyone under the age of 18. If you are a parent or guardian and you are aware that your child has provided us with personal data, please contact us.",
    privacyChanges: "10. Changes to This Privacy Policy",
    privacyChangesText1: "We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page and updating the Last updated date.",
    privacyChangesText2: "You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.",
    privacyContactTitle: "11. Contact Us",
    privacyContactText: "If you have any questions about this Privacy Policy, please contact us through our official communication channels.",
  },
  "zh-CN": {
    community: "社区",
    developers: "开发者",
    launchApp: "启动应用",
    heroTitle: "流动性无处不在",
    heroSubtitle: "释放您的交易优势",
    volume24h: "24小时交易量",
    cumulativeVolume: "累计交易量",
    addresses: "地址数",
    dexTitle: "去中心化交易所，超快速无缝交易体验",
    startTrading: "开始交易",
    lowFees: "低手续费",
    minimalSlippage: "最小滑点",
    selfCustody: "自托管",
    lightningFast: "闪电般快速执行",
    tradeTitle: "随时随地交易",
    tradeDescription: "随时随地访问Perpolis。快速、可靠，专为专业交易者打造。",
    featuresTitle: "面向所有人的高性能交易",
    featuresSubtitle: "为深度流动性、速度和安全性而设计的强大交易引擎",
    ultraDeepLiquidity: "超深流动性",
    ultraDeepDesc: "您的会话是隔离的且受到全面保护。在安全的环境中自信交易。",
    highPerformance: "高性能",
    highPerformanceDesc: "每秒20万笔以上订单，延迟低于10毫秒。",
    provenSecurity: "经过验证的安全性",
    provenSecurityDesc: "由以太坊主网保护。您的密钥。您的资产。",
    oneAppUnlimited: "一个应用，无限DeFi体验",
    oneAppDesc: "多链、多协议、一个平台。",
    roadmapTitle: "路线图",
    roadmapSubtitle: "高性能链上金融系统",
    q1: "第一季度",
    q1Title: "Perpolis V1 发布",
    q1Desc: "网页和移动应用程序发布",
    q2: "第二季度",
    q2Title: "eStrategy：链上资产管理",
    q2Desc: "eLP和交易策略金库发布",
    q3: "第三季度",
    q3Title: "社交交易功能",
    q3Desc: "区块链测试网发布",
    q4: "第四季度",
    q4Title: "无许可流动性模块发布",
    q4Desc: "任何人都可以创建、管理和部署流动性策略",
    teamTitle: "我们的团队来自",
    footerTagline: "去中心化交易所，超快速无缝交易体验",
    products: "产品",
    spotTrading: "现货交易",
    futuresTrading: "期货交易",
    eStrategy: "eStrategy",
    earn: "收益",
    resources: "资源",
    documentation: "文档",
    api: "API",
    github: "GitHub",
    blog: "博客",
    legal: "法律",
    termsOfService: "服务条款",
    privacyPolicy: "隐私政策",
    cookiePolicy: "Cookie政策",
    copyright: "© 2026 Perpolis. 版权所有。",
    builtForTraders: "为交易者打造，由交易者打造。",
    termsTitle: "服务条款",
    termsAcceptance: "1. 接受条款",
    termsAcceptanceText: "通过访问和使用Perpolis，您接受并同意受本协议条款和规定的约束。",
    termsLicense: "2. 使用许可",
    termsLicenseText: "仅授予临时访问权限以供个人非商业性临时查看。",
    termsLicenseRestrictions: "在此许可下，您不得：",
    termsLicenseList1: "修改或复制材料",
    termsLicenseList2: "将材料用于任何商业目的",
    termsLicenseList3: "尝试进行反向工程",
    termsLicenseList4: "删除版权标记",
    termsRisks: "3. 交易风险",
    termsRisksText1: "交易加密货币具有高度风险。",
    termsRisksText2: "您可能会损失全部投资。",
    termsAccounts: "4. 用户账户",
    termsAccountsText1: "您必须提供准确的信息。",
    termsAccountsText2: "您负责保护密码。",
    termsProhibited: "5. 禁止活动",
    termsProhibitedText: "禁止的活动包括�����",
    termsProhibitedList1: "市场操纵",
    termsProhibitedList2: "未授权交易",
    termsProhibitedList3: "干扰平台运行",
    termsProhibitedList4: "规避安全功能",
    termsProhibitedList5: "洗钱活动",
    termsLiability: "6. 责任限制",
    termsLiabilityText: "我们不对任何损害负责。",
    termsModifications: "7. 修改",
    termsModificationsText: "我们可随时修改条款。",
    termsContact: "8. 联系信息",
    termsContactText: "如有疑问，请联系我们。",
    lastUpdated: "最后更新：2026年4月",
    privacyTitle: "隐私政策",
    privacyCollection: "1. 信息收集",
    privacyCollectionText: "我们收集各种信息。",
    privacyPersonalData: "个人数据",
    privacyPersonalDataText: "包括以下信息：",
    privacyDataList1: "电子邮件",
    privacyDataList2: "钱包地址",
    privacyDataList3: "交易数据",
    privacyDataList4: "设备信息",
    privacyDataList5: "IP地址",
    privacyUsage: "2. 信息使用",
    privacyUsageText: "用于以下目的：",
    privacyUsageList1: "提供服务",
    privacyUsageList2: "通知变更",
    privacyUsageList3: "客户支持",
    privacyUsageList4: "防止欺诈",
    privacyUsageList5: "遵守法律",
    privacyUsageList6: "改进服务",
    privacySecurity: "3. 数据安全",
    privacySecurityText1: "我们保护您的数据。",
    privacySecurityText2: "安全措施包括：",
    privacySecurityList1: "数据加密",
    privacySecurityList2: "安全审计",
    privacySecurityList3: "多因素认证",
    privacySecurityList4: "冷存储",
    privacySecurityList5: "访问控制",
    privacyCookies: "4. Cookie",
    privacyCookiesText1: "我们使用Cookie。",
    privacyCookiesText2: "您可以拒绝Cookie。",
    privacyThirdParty: "5. 第三方服务",
    privacyThirdPartyText1: "我们使用第三方服务。",
    privacyThirdPartyText2: "他们有权访问数据。",
    privacyRetention: "6. 数据保留",
    privacyRetentionText: "我们保留必要的数据。",
    privacyRights: "7. 数据权利",
    privacyRightsText: "您拥有以下权利：",
    privacyRightsList1: "访问数据",
    privacyRightsList2: "更正数据",
    privacyRightsList3: "反对处理",
    privacyRightsList4: "限制处理",
    privacyRightsList5: "数据可携",
    privacyRightsList6: "撤回同意",
    privacyTransfers: "8. 国际传输",
    privacyTransfersText: "数据可能跨境传输。",
    privacyChildren: "9. 儿童隐私",
    privacyChildrenText: "不针对18岁以下用户。",
    privacyChanges: "10. 政策变更",
    privacyChangesText1: "我们可能更新政策。",
    privacyChangesText2: "请定期查看。",
    privacyContactTitle: "11. 联系我们",
    privacyContactText: "如有疑问请联系。",
  },
  "zh-TW": {
    community: "社群",
    developers: "開發者",
    launchApp: "啟動應用",
    heroTitle: "流動性無處不在",
    heroSubtitle: "釋放您的交易優勢",
    volume24h: "24小時交易量",
    cumulativeVolume: "累計交易量",
    addresses: "地址數",
    dexTitle: "去中心化交易所，超快速無縫交易體驗",
    startTrading: "開始交易",
    lowFees: "低手續費",
    minimalSlippage: "最小滑點",
    selfCustody: "自託管",
    lightningFast: "閃電般快速執行",
    tradeTitle: "隨時隨地交易",
    tradeDescription: "隨時隨地訪問Perpolis。快速、可靠，專為專業交易者打造。",
    featuresTitle: "面向所有人的高性能交易",
    featuresSubtitle: "為深度流動性、速度和安全性而設計的強大交易引擎",
    ultraDeepLiquidity: "超深流動性",
    ultraDeepDesc: "您的會話是隔離的且受到全面保護。在安全的環境中自信交易。",
    highPerformance: "高性能",
    highPerformanceDesc: "每秒20萬筆以上訂單，延遲低於10毫秒。",
    provenSecurity: "經過驗證的安全性",
    provenSecurityDesc: "由以太坊主網保護。您的密鑰。您的資產。",
    oneAppUnlimited: "一個應用，無限DeFi體驗",
    oneAppDesc: "多鏈、多協議、一個平台。",
    roadmapTitle: "路線圖",
    roadmapSubtitle: "高性能鏈上金融系統",
    q1: "第一季度",
    q1Title: "Perpolis V1 發布",
    q1Desc: "網頁和移動應用程序發布",
    q2: "第二季度",
    q2Title: "eStrategy：鏈上資產管理",
    q2Desc: "eLP和交易策略金庫發布",
    q3: "第三季度",
    q3Title: "社交交易功能",
    q3Desc: "區塊鏈測試網發布",
    q4: "第四季度",
    q4Title: "無許可流動性模塊發布",
    q4Desc: "任何人都可以創建、管理和部署流動性策略",
    teamTitle: "我們的團隊來自",
    footerTagline: "去中心化交易所，超快速無縫交易體驗",
    products: "產品",
    spotTrading: "現貨交易",
    futuresTrading: "期貨交易",
    eStrategy: "eStrategy",
    earn: "收益",
    resources: "資源",
    documentation: "文檔",
    api: "API",
    github: "GitHub",
    blog: "博客",
    legal: "法律",
    termsOfService: "服務條款",
    privacyPolicy: "隱私政策",
    cookiePolicy: "Cookie政策",
    copyright: "© 2026 Perpolis. 版權所有。",
    builtForTraders: "為交易者打造，由交易者打造。",
    termsTitle: "服務條款",
    termsAcceptance: "1. 接受條款",
    termsAcceptanceText: "通過訪問和使用Perpolis，您接受並同意受本協議條款和規定的約束。",
    termsLicense: "2. 使用許可",
    termsLicenseText: "僅授予臨時訪問權限以供個人非商業性臨時查看。",
    termsLicenseRestrictions: "在此許可下，您不得：",
    termsLicenseList1: "修改或複製材料",
    termsLicenseList2: "將材料用於任何商業目的",
    termsLicenseList3: "嘗試進行反向工程",
    termsLicenseList4: "刪除版權標記",
    termsRisks: "3. 交易風險",
    termsRisksText1: "交易加密貨幣具有高度風險。",
    termsRisksText2: "您可能會損失全部投資。",
    termsAccounts: "4. 用戶賬戶",
    termsAccountsText1: "您必須提供準確的信息。",
    termsAccountsText2: "您負責保護密碼。",
    termsProhibited: "5. 禁止活動",
    termsProhibitedText: "禁止的活動包括：",
    termsProhibitedList1: "市場操縱",
    termsProhibitedList2: "未授權交易",
    termsProhibitedList3: "干擾平台運行",
    termsProhibitedList4: "規避安全功能",
    termsProhibitedList5: "洗錢活動",
    termsLiability: "6. 責任限制",
    termsLiabilityText: "我們不對任何損害負責。",
    termsModifications: "7. 修改",
    termsModificationsText: "我們可隨時修改條款。",
    termsContact: "8. 聯繫信息",
    termsContactText: "如有疑問，請聯繫我們。",
    lastUpdated: "最後更新：2026年4月",
    privacyTitle: "隱私政策",
    privacyCollection: "1. 信息收集",
    privacyCollectionText: "我們收集各種信息。",
    privacyPersonalData: "個人數據",
    privacyPersonalDataText: "包括以下信息：",
    privacyDataList1: "電子郵件",
    privacyDataList2: "錢包地址",
    privacyDataList3: "交易數據",
    privacyDataList4: "設備信息",
    privacyDataList5: "IP地址",
    privacyUsage: "2. 信息使用",
    privacyUsageText: "用於以下目的：",
    privacyUsageList1: "提供服務",
    privacyUsageList2: "通知變更",
    privacyUsageList3: "客戶支持",
    privacyUsageList4: "防止欺詐",
    privacyUsageList5: "遵守法律",
    privacyUsageList6: "改進服務",
    privacySecurity: "3. 數據安全",
    privacySecurityText1: "我們保護您的數據。",
    privacySecurityText2: "安全措施包括：",
    privacySecurityList1: "數據加密",
    privacySecurityList2: "安全審計",
    privacySecurityList3: "多因素認證",
    privacySecurityList4: "冷存儲",
    privacySecurityList5: "訪問控制",
    privacyCookies: "4. Cookie",
    privacyCookiesText1: "我們使用Cookie。",
    privacyCookiesText2: "您可以拒絕Cookie。",
    privacyThirdParty: "5. 第三方服務",
    privacyThirdPartyText1: "我們使用第三方服務。",
    privacyThirdPartyText2: "他們有權訪問數據。",
    privacyRetention: "6. 數據保留",
    privacyRetentionText: "我們保留必要的數據。",
    privacyRights: "7. 數據權利",
    privacyRightsText: "您擁有以下權利：",
    privacyRightsList1: "訪問數據",
    privacyRightsList2: "更正數據",
    privacyRightsList3: "反對處理",
    privacyRightsList4: "限制處理",
    privacyRightsList5: "數據可攜",
    privacyRightsList6: "撤回同意",
    privacyTransfers: "8. 國際傳輸",
    privacyTransfersText: "數據可能跨境傳輸。",
    privacyChildren: "9. 兒童隱私",
    privacyChildrenText: "不針對18歲以下用戶。",
    privacyChanges: "10. 政策變更",
    privacyChangesText1: "我們可能更新政策。",
    privacyChangesText2: "請定期查看。",
    privacyContactTitle: "11. 聯繫我們",
    privacyContactText: "如有疑問請聯繫。",
  },
  ja: {
    community: "コミュニティ",
    developers: "開発者",
    launchApp: "アプリを起動",
    heroTitle: "すべての人に流動性を",
    heroSubtitle: "トレーディングの優位性を解き放つ",
    volume24h: "24時間取引高",
    cumulativeVolume: "累積取引高",
    addresses: "アドレス数",
    dexTitle: "超高速でシームレスな取引体験を備えた分散型取引所",
    startTrading: "取引を始める",
    lowFees: "低手数料",
    minimalSlippage: "最小スリッページ",
    selfCustody: "セルフカストディ",
    lightningFast: "高速執行",
    tradeTitle: "いつでもどこでも取引",
    tradeDescription: "いつでもどこでもPerpolisにアクセス。高速で信頼性が高く、プロのトレーダー向けに構築されています。",
    featuresTitle: "すべての人のための高性能トレーディング",
    featuresSubtitle: "深い流動性、スピード、セキュリティのために設計された強力な取引エンジン",
    ultraDeepLiquidity: "超深流動性",
    ultraDeepDesc: "セッションは分離され、完全に保護されています。安全な環境で自信を持って取引してください。",
    highPerformance: "高性能",
    highPerformanceDesc: "毎秒20万以上の注文、10ms未満のレイテンシ。",
    provenSecurity: "実証済みのセキュリティ",
    provenSecurityDesc: "イーサリアムメインネットによって保護されています。あなたの鍵。あなたの資産。",
    oneAppUnlimited: "1つのアプリ、無限のDeFi体験",
    oneAppDesc: "マルチチェーン、マルチプロトコル、1つのプラットフォーム。",
    roadmapTitle: "ロードマップ",
    roadmapSubtitle: "高性能オンチェーン金融システム",
    q1: "第1四半期",
    q1Title: "Perpolis V1 リリース",
    q1Desc: "Webおよびモバイルアプリケーションのローンチ",
    q2: "第2四半期",
    q2Title: "eStrategy：オンチェーン資産管理",
    q2Desc: "eLPおよび取引戦略ボルトのローンチ",
    q3: "第3四半期",
    q3Title: "ソーシャルトレーディング機能",
    q3Desc: "ブロックチェーンテストネットのローンチ",
    q4: "第4四半期",
    q4Title: "パーミッションレス流動性モジュールのローンチ",
    q4Desc: "誰でも流動性戦略を作成、管理、デプロイできます",
    teamTitle: "私たちのチームの出身",
    footerTagline: "超高速でシームレスな取引体験を備えた分散型取引所",
    products: "製品",
    spotTrading: "スポット取引",
    futuresTrading: "先物取引",
    eStrategy: "eStrategy",
    earn: "稼ぐ",
    resources: "リソース",
    documentation: "ドキュメント",
    api: "API",
    github: "GitHub",
    blog: "ブログ",
    legal: "法的",
    termsOfService: "利用規約",
    privacyPolicy: "プライバシーポリシー",
    cookiePolicy: "Cookieポリシー",
    copyright: "© 2026 Perpolis. 全著作権所有。",
    builtForTraders: "トレーダーのために、トレーダーによって構築されました。",
    termsTitle: "利用規約",
    termsAcceptance: "1. 規約への同意",
    termsAcceptanceText: "Perpolisにアクセスして使用することにより、本契約の条項と規定に拘束されることに同意します。",
    termsLicense: "2. 使用許可",
    termsLicenseText: "個人的な非商用の一時的な閲覧のための一時的なアクセス権が付与されます。",
    termsLicenseRestrictions: "このライセンスの下では、以下を行うことはできません：",
    termsLicenseList1: "資料の変更またはコピー",
    termsLicenseList2: "商用目的での使用",
    termsLicenseList3: "リバースエンジニアリング",
    termsLicenseList4: "著作権表示の削除",
    termsRisks: "3. 取引リスク",
    termsRisksText1: "暗号通貨の取引には高いリスクがあります。",
    termsRisksText2: "全投資額を失う可能性があります。",
    termsAccounts: "4. ユーザーアカウント",
    termsAccountsText1: "正確な情報を提供する必要があります。",
    termsAccountsText2: "パスワードの保護はあなたの責任です。",
    termsProhibited: "5. 禁止行為",
    termsProhibitedText: "禁止されている活動には以下が含まれます：",
    termsProhibitedList1: "市場操作",
    termsProhibitedList2: "無許可の取引",
    termsProhibitedList3: "プラットフォームへの妨害",
    termsProhibitedList4: "セキュリティ機能の回避",
    termsProhibitedList5: "マネーロンダリング",
    termsLiability: "6. 責任の制限",
    termsLiabilityText: "いかなる損害についても責任を負いません。",
    termsModifications: "7. 変更",
    termsModificationsText: "規約を随時変更できます。",
    termsContact: "8. 連絡先情報",
    termsContactText: "ご質問がある場合はお問い合わせください。",
    lastUpdated: "最終更新：2026年4月",
    privacyTitle: "プライバシーポリシー",
    privacyCollection: "1. 収集する情報",
    privacyCollectionText: "さまざまな情報を収集します。",
    privacyPersonalData: "個人データ",
    privacyPersonalDataText: "以下の情報が含まれます：",
    privacyDataList1: "メールアドレス",
    privacyDataList2: "ウォレットアドレス",
    privacyDataList3: "取引データ",
    privacyDataList4: "デバイス情報",
    privacyDataList5: "IPアドレス",
    privacyUsage: "2. 情報の使用",
    privacyUsageText: "以下の目的で使用します：",
    privacyUsageList1: "サービス提供",
    privacyUsageList2: "��更��知",
    privacyUsageList3: "カスタマーサポート",
    privacyUsageList4: "不正防止",
    privacyUsageList5: "法令遵守",
    privacyUsageList6: "サービス改善",
    privacySecurity: "3. データセキュリティ",
    privacySecurityText1: "データを保護します。",
    privacySecurityText2: "セキュリティ対策：",
    privacySecurityList1: "データ暗号化",
    privacySecurityList2: "セキュリティ監査",
    privacySecurityList3: "多要素認証",
    privacySecurityList4: "コールドストレージ",
    privacySecurityList5: "アクセス制御",
    privacyCookies: "4. Cookie",
    privacyCookiesText1: "Cookieを使用します。",
    privacyCookiesText2: "Cookieを拒否できます。",
    privacyThirdParty: "5. 第三者サービス",
    privacyThirdPartyText1: "第三者サービスを使用します。",
    privacyThirdPartyText2: "データへのアクセス権があります。",
    privacyRetention: "6. データ保持",
    privacyRetentionText: "必要なデータを保持します。",
    privacyRights: "7. データ権利",
    privacyRightsText: "以下の権利があります：",
    privacyRightsList1: "データアクセス",
    privacyRightsList2: "データ修正",
    privacyRightsList3: "処理への異議",
    privacyRightsList4: "処理の制限",
    privacyRightsList5: "データポータビリティ",
    privacyRightsList6: "同意の撤回",
    privacyTransfers: "8. 国際転送",
    privacyTransfersText: "データは国際的に転送される場合があります。",
    privacyChildren: "9. 子供のプライバシー",
    privacyChildrenText: "18歳未満を対象としていません。",
    privacyChanges: "10. ポリシーの変更",
    privacyChangesText1: "ポリシーを更新する場合があります。",
    privacyChangesText2: "定期的にご確認ください。",
    privacyContactTitle: "11. お問い合わせ",
    privacyContactText: "ご質問がある場合はお問い合わせください。",
  },
  ru: {
    community: "Сообщество",
    developers: "Разработчики",
    launchApp: "Запустить приложение",
    heroTitle: "Ликвидность для всех",
    heroSubtitle: "Раскройте свое торговое преимущество",
    volume24h: "Объем за 24ч",
    cumulativeVolume: "Совокупный объем",
    addresses: "Адреса",
    dexTitle: "Децентрализованная биржа с ультрабыстрым бесшовным торговым опытом",
    startTrading: "Начать торговлю",
    lowFees: "Низкие комиссии",
    minimalSlippage: "Минимальное проскальзывание",
    selfCustody: "Самостоятельное хранение",
    lightningFast: "Молниеносное исполнение",
    tradeTitle: "Торгуйте в любое время и в любом месте",
    tradeDescription: "Доступ к Perpolis с любого устройства. Быстро, надёжно и создано для профессиональных трейдеров.",
    featuresTitle: "Высокопроизводительная торговля для всех",
    featuresSubtitle: "Мощный торговый движок, разработанный для глубокой ликвидности, скорости и безопасности",
    ultraDeepLiquidity: "Сверхглубокая ликвидность",
    ultraDeepDesc: "Ваши сессии изолированы и полностью защищены. Торгуйте с уверенностью в безопасной среде.",
    highPerformance: "Высокая производительность",
    highPerformanceDesc: "Более 200 000 ордеров в секунду, задержка менее 10 мс.",
    provenSecurity: "Проверенная безопасность",
    provenSecurityDesc: "Защищено основной сетью Ethereum. Ваши ключи. Ваши активы.",
    oneAppUnlimited: "Одно приложение, неограниченный опыт DeFi",
    oneAppDesc: "Мультичейн, мультипротокол, одна платформа.",
    roadmapTitle: "Дорожная карта",
    roadmapSubtitle: "Высокопроизводительная финансовая система на блокчейне",
    q1: "1 квартал",
    q1Title: "Запуск Perpolis V1",
    q1Desc: "Запуск веб- и мобильных приложений",
    q2: "2 квартал",
    q2Title: "eStrategy: Управление активами на блокчейне",
    q2Desc: "Запуск eLP и хранилищ торговых стратегий",
    q3: "3 квартал",
    q3Title: "Социальный трейдинг",
    q3Desc: "Запуск тестовой сети блокчейна",
    q4: "4 квартал",
    q4Title: "Запуск модулей ликвидности без разрешений",
    q4Desc: "Любой может создавать, управлять и развертывать стратегии ликвидности",
    teamTitle: "Наша команда из",
    footerTagline: "Децентрализованная биржа с ультрабыстрым бесшовным торговым опытом",
    products: "Продукты",
    spotTrading: "Спотовая торговля",
    futuresTrading: "Фьючерсная торговля",
    eStrategy: "eStrategy",
    earn: "Заработок",
    resources: "Ресурсы",
    documentation: "Документация",
    api: "API",
    github: "GitHub",
    blog: "Блог",
    legal: "Юридическое",
    termsOfService: "Условия обслуживания",
    privacyPolicy: "Политика конфиденциальности",
    cookiePolicy: "Политика использования файлов cookie",
    copyright: "© 2026 Perpolis. Все права защищены.",
    builtForTraders: "Создано трейдерами для трейдеров.",
    termsTitle: "Условия обслуживания",
    termsAcceptance: "1. Принятие условий",
    termsAcceptanceText: "Используя Perpolis, вы соглашаетесь с условиями данного соглашения.",
    termsLicense: "2. Лицензия на использование",
    termsLicenseText: "Предоставляется временный доступ для личного некоммерческого использования.",
    termsLicenseRestrictions: "Вам запрещено:",
    termsLicenseList1: "Изменять материалы",
    termsLicenseList2: "Коммерческое использование",
    termsLicenseList3: "Обратная разработка",
    termsLicenseList4: "Удаление авторских прав",
    termsRisks: "3. Торговые риски",
    termsRisksText1: "Торговля криптовалютой несет высокий риск.",
    termsRisksText2: "Вы можете потерять все инвестиции.",
    termsAccounts: "4. Учетные записи",
    termsAccountsText1: "Вы должны предоставлять точную информацию.",
    termsAccountsText2: "Вы несете ответственность за пароль.",
    termsProhibited: "5. Запрещенная деятельность",
    termsProhibitedText: "Запрещены следующие действия:",
    termsProhibitedList1: "Манипулирование рынком",
    termsProhibitedList2: "Не��анкционированная торговля",
    termsProhibitedList3: "Вмешательство в работу",
    termsProhibitedList4: "Обход безопасности",
    termsProhibitedList5: "Отмывание денег",
    termsLiability: "6. Ограничение ответственности",
    termsLiabilityText: "Мы не несем ответственности за любой ущерб.",
    termsModifications: "7. Изменения",
    termsModificationsText: "Мы можем изменять условия в любое время.",
    termsContact: "8. Контактная информация",
    termsContactText: "По вопросам свяжитесь с нами.",
    lastUpdated: "Последнее обновление: апрель 2026",
    privacyTitle: "Политика конфиденциальности",
    privacyCollection: "1. Сбор информации",
    privacyCollectionText: "Мы собираем различную информацию.",
    privacyPersonalData: "Личные данные",
    privacyPersonalDataText: "Включает следующее:",
    privacyDataList1: "Электронная почта",
    privacyDataList2: "Адреса кошельков",
    privacyDataList3: "Данные транзакций",
    privacyDataList4: "Информация об устройстве",
    privacyDataList5: "IP-адрес",
    privacyUsage: "2. Использование информации",
    privacyUsageText: "Для следующих целей:",
    privacyUsageList1: "Предоставление услуг",
    privacyUsageList2: "Уведомления об изменениях",
    privacyUsageList3: "Поддержка клиентов",
    privacyUsageList4: "Предотвращение мошенничества",
    privacyUsageList5: "Соблюдение законов",
    privacyUsageList6: "Улучшение сервиса",
    privacySecurity: "3. Безопасность данных",
    privacySecurityText1: "Мы защищаем ваши данные.",
    privacySecurityText2: "Меры безопасности:",
    privacySecurityList1: "Шифрование данных",
    privacySecurityList2: "Аудит безопасности",
    privacySecurityList3: "Многофакторная аутентификация",
    privacySecurityList4: "Холодное хранилище",
    privacySecurityList5: "Контроль доступа",
    privacyCookies: "4. Файлы cookie",
    privacyCookiesText1: "Мы используем файлы cookie.",
    privacyCookiesText2: "Вы можете отказаться от cookie.",
    privacyThirdParty: "5. Сторонние сервисы",
    privacyThirdPartyText1: "Мы используем сторонние сервисы.",
    privacyThirdPartyText2: "Они имеют доступ к данным.",
    privacyRetention: "6. Хранение данных",
    privacyRetentionText: "Мы храним необходимые данные.",
    privacyRights: "7. Права на данные",
    privacyRightsText: "У вас есть следующие права:",
    privacyRightsList1: "Доступ к данным",
    privacyRightsList2: "Исправление данных",
    privacyRightsList3: "Возражение против обработки",
    privacyRightsList4: "Ограничение обработки",
    privacyRightsList5: "Портативность данных",
    privacyRightsList6: "Отзыв согласия",
    privacyTransfers: "8. Международная передача",
    privacyTransfersText: "Данные могут передаваться за границу.",
    privacyChildren: "9. Конфиденциальность детей",
    privacyChildrenText: "Не предназначено для лиц младше 18 лет.",
    privacyChanges: "10. Изменения политики",
    privacyChangesText1: "Мы можем обновлять политику.",
    privacyChangesText2: "Проверяйте регулярно.",
    privacyContactTitle: "11. Связаться с нами",
    privacyContactText: "По вопросам свяжитесь с нами.",
  },
}

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>("en")

  useEffect(() => {
    const savedLang = localStorage.getItem("perpolis-language") as Language
    if (savedLang && translations[savedLang]) {
      setLanguageState(savedLang)
    }
  }, [])

  const setLanguage = (lang: Language) => {
    setLanguageState(lang)
    localStorage.setItem("perpolis-language", lang)
  }

  const t = (key: string): string => {
    return translations[language][key] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider")
  }
  return context
}
